# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 573b162e7f716c30753100a6d5305cf772c25eefd030c80ade27836048672ac3de73da4c53623dc8438560d7816eefc7b7f89d5e63f2052caa96d7601e63c0cf

test:
  secret_key_base: 905a10b537250ba5828f9062d579600e8b310250570665b2deb2e06aca380d7382e0b1d495f3a7805707e5d51116a95ab023a56c942b428f690a355080e0352f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
